api_platform:
    title: 'Starter Kit API'
    description: 'API du starter kit Symfony 8.1 (API Platform 4) + React 19.'
    version: '%env(APP_VERSION)%'
    defaults:
        stateless: true
        pagination_enabled: true
        pagination_items_per_page: 10
        pagination_maximum_items_per_page: 100
        pagination_client_items_per_page: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']